services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    networks:
      - app-network

  postgresql-jsonb-index:
    image: 'postgresql-jsonb-index/postgresql-jsonb-index:0.0.1-SNAPSHOT'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase'
    ports:
      - '8080:8080'
    networks:
      - app-network
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge
